-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Mar 31, 2022 at 02:59 PM
-- Server version: 5.7.37
-- PHP Version: 7.4.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ta459_alchomist`
--

-- --------------------------------------------------------

--
-- Table structure for table `cocktails`
--

CREATE TABLE `cocktails` (
  `cocktailID` int(11) NOT NULL,
  `creatorID` int(11) DEFAULT NULL,
  `cocktailName` tinytext NOT NULL,
  `recipe` json NOT NULL,
  `image` tinytext,
  `category` tinytext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `cocktails`
--

INSERT INTO `cocktails` (`cocktailID`, `creatorID`, `cocktailName`, `recipe`, `image`, `category`) VALUES
(1, NULL, 'Alexander', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.\", \"Garnish\": \"Sprinkle fresh ground nutmeg on top.\", \"Ingredients\": {\"Cognac\": \"30 ml\", \"Fresh Cream\": \"30 ml\", \"Creme de Cacao (Brown)\": \"30 ml\"}}]}', 'Alexander.jpg', 'The Unforgettables'),
(2, NULL, 'Americano', '{\"recipe\": [{\"Method\": \"Mix the ingredients directly in an old fashioned glass filled with ice cubes. Add a splash of Soda Water. Stir gently.\", \"Garnish\": \"Garnish with half orange slice and a lemon zest.\", \"Ingredients\": {\"Soda Water\": \"A splash\", \"Bitter Campari\": \"30 ml\", \"Sweet Red Vermouth\": \"30 ml\"}}]}', 'Americano.jpg', 'The Unforgettables'),
(3, NULL, 'Angel Face', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Gin\": \"30 ml\", \"Calvados\": \"30 ml\", \"Apricot Brandy\": \"30 ml\"}}]}', 'Angel-Face.jpg', 'The Unforgettables'),
(4, NULL, 'Aviation', '{\"recipe\": [{\"Method\": \"Add all ingredients into a cocktail shaker. Shake with cracked ice and strain into a chilled cocktail glass.\", \"Garnish\": \"Optional Maraschino Cherry.\", \"Ingredients\": {\"Gin\": \"45ml\", \"Creme de Violette\": \"1 Bar Spoon\", \"Fresh Lemon Juice\": \"15 ml\", \"Maraschino Luxardo\": \"15ml\"}}]}', 'Aviation.jpg', 'The Unforgettables'),
(5, NULL, 'Between The Sheets', '{\"recipe\": [{\"Method\": \"Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Cognac\": \"30 ml\", \"White Rum\": \"30 ml\", \"Triple Sec\": \"30 ml\", \"Fresh Lemon Juice\": \"20 ml\"}}]}', 'Between-The-Sheets.jpg', 'The Unforgettables'),
(6, NULL, 'Boulevadier', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.\", \"Garnish\": \"Garnish with orange zest, optionally a lemon zest.\", \"Ingredients\": {\"Bitter Campari\": \"30 ml\", \"Sweet Red Vermouth\": \"30 ml\", \"Bourbon or Rye Whiskey\": \"45 ml\"}}]}', 'Boulevadier.jpg', 'The Unforgettables'),
(7, NULL, 'Brandy Crusta', '{\"recipe\": [{\"Method\": \"Mix together all ingredients with ice cubes in a mixing glass and strain into prepared slim cocktail glass.\", \"Garnish\": \"Rub a slice of orange (or lemon) around the rim of the glass and dip it in pulverized white sugar, so that the sugar will adhere to the edge of the glass. Carefully curling place the orange/lemon peel around the inside of the glass.\", \"Ingredients\": {\"Brandy\": \"52.5 ml\", \"Curacao\": \"1 Bar Spoon\", \"Simple Syrup\": \"1 Bar Spoon\", \"Aromatic Bitters\": \"2 Dashes\", \"Fresh Lemon Juice\": \"15 ml\", \"Maraschino Luxardo\": \"7.5 ml\"}}]}', 'Brandy-Crusta.jpg', 'The Unforgettables'),
(8, NULL, 'Casino', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled rocks glass with ice.\", \"Garnish\": \"Garnish with lemon zest and a maraschino cherry.\", \"Ingredients\": {\"Old Tom Gin\": \"40 ml\", \"Orange Bitters\": \"2 Dashes\", \"Fresh Lemon Juice\": \"10 ml\", \"Maraschino Luxardo\": \"10 ml\"}}]}', 'Casino.jpg', 'The Unforgettables'),
(9, NULL, 'Clover Club', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktails shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"Fresh raspberries.\", \"Ingredients\": {\"Gin\": \"45 ml\", \"Egg White\": \"A Few Drops\", \"Raspberry Syrup\": \"15 ml\", \"Fresh Lemon Juice\": \"15 ml\"}}]}', 'Clover-Club.jpg', 'The Unforgettables'),
(10, NULL, 'Daiquiri', '{\"recipe\": [{\"Method\": \"In a cocktail shaker add all ingredients. Stir well to dissolve the sugar. Add ice and shake. Strain into chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Superfine Sugar\": \"2 Bar Spoons\", \"White Cuban Ron\": \"60 ml\", \"Fresh Lime Juice\": \"20 ml\"}}]}', 'Daiquiri.jpg', 'The Unforgettables'),
(11, NULL, 'Dry Martini', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.\", \"Garnish\": \"Squeeze oil from lemon peel onto the drink, or garnish with green olives if requested.\", \"Ingredients\": {\"Gin\": \"60 ml\", \"Dry Vermouth\": \"20 ml\"}}]}', 'Dry-Martini.jpg', 'The Unforgettables'),
(12, NULL, 'Gin Fizz', '{\"recipe\": [{\"Method\": \"Shake all ingredients with ice except soda water. Pour into thin tall Tumbler glass, top with a splash soda water. NOTE: Serve without ice.\", \"Garnish\": \"Garnish with a lemon slice, optional lemon zest.\", \"Ingredients\": {\"Gin\": \"45 ml\", \"Soda Water\": \"A splash\", \"Simple Syrup\": \"10 ml\", \"Fresh Lemon Juice\": \"30 ml\"}}]}', 'Gin-Fizz.jpg', 'The Unforgettables'),
(13, NULL, 'Hanky Panky', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled cocktail glass.\", \"Garnish\": \"Orange zest.\", \"Ingredients\": {\"Fernet Branca\": \"7.5 ml\", \"London Dry Gin\": \"45 ml\", \"Sweet Red Vermouth\": \"45 ml\"}}]}', 'Hanky-Panky.jpg', 'The Unforgettables'),
(14, NULL, 'John Collins', '{\"recipe\": [{\"Method\": \"Pour all ingredients directly into a highball filled with ice. Stir gently. NOTE: Use Old Tom Gin for Tom Collins.\", \"Garnish\": \"Garnish with a lemon slice and maraschino cherry.\", \"Ingredients\": {\"Gin\": \"45 ml\", \"Soda Water\": \"60 ml\", \"Simple Syrup\": \"15 ml\", \"Fresh Lemon Juice\": \"30 ml\"}}]}', 'John-Collins.jpg', 'The Unforgettables'),
(15, NULL, 'Last Word', '{\"recipe\": [{\"Method\": \"Add all ingredients into a cocktail shaker. Shake with ice and strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Gin\": \"22.5 ml\", \"Fresh Lime Juice\": \"22.5 ml\", \"Green Chartreuse\": \"22.5 ml\", \"Maraschino Luxardo\": \"22.5 ml\"}}]}', 'Last-Word.jpg', 'The Unforgettables'),
(16, NULL, 'Manhattan', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.\", \"Garnish\": \"Garnish with a cocktail cherry.\", \"Ingredients\": {\"Rye Whiskey\": \"50 ml\", \"Angostura Bitters\": \"1 Dash\", \"Sweet Red Vermouth\": \"20 ml\"}}]}', 'Manhattan.jpg', 'The Unforgettables'),
(17, NULL, 'Martinez', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.\", \"Garnish\": \"Lemon zest.\", \"Ingredients\": {\"London Dry Gin\": \"45 ml\", \"Orange Bitters\": \"2 Dashes\", \"Maraschino Liqueur\": \"1 Bar Spoon\", \"Sweet Red Vermouth\": \"45 ml\"}}]}', 'Martinez.jpg', 'The Unforgettables'),
(18, NULL, 'Mary Pickford', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"White Rum\": \"45 ml\", \"Grenadine Syrup\": \"5 ml\", \"Maraschino Luxardo\": \"7.5 ml\", \"Fresh Pineapple Juice\": \"45 ml\"}}]}', 'Mary-Pickford.jpg', 'The Unforgettables'),
(19, NULL, 'Monkey Gland', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Dry Gin\": \"45 ml\", \"Absinthe\": \"1 Table Spoon\", \"Grenadine Syrup\": \"1 Table Spoon\", \"Fresh Orange Juice\": \"45 ml\"}}]}', 'Monkey-Gland.jpg', 'The Unforgettables'),
(20, NULL, 'Negroni', '{\"recipe\": [{\"Method\": \"Pour all ingredients directly into a chilled old fashioned glass filled with ice, Stir gently.\", \"Garnish\": \"Garnish with a half orange slice.\", \"Ingredients\": {\"Gin\": \"30 ml\", \"Bitter Campari\": \"30 ml\", \"Sweet Red Vermouth\": \"30 ml\"}}]}', 'Negroni.jpg', 'The Unforgettables'),
(21, NULL, 'Old Fashioned', '{\"recipe\": [{\"Method\": \"Place sugar cube in old fashioned glass and saturate with bitter, add few dashes of plain water. Muddle until dissolved. Fill the glass with ice cubes and add whiskey. Stir gently.\", \"Garnish\": \"Garnish with an orange slice or zest, and a cocktail cherry.\", \"Ingredients\": {\"Water\": \"3 Dashes\", \"Sugar Cube\": \"1\", \"Angostura Bitters\": \"3 Dashes\", \"Bourbon or Rye Whiskey\": \"45 ml\"}}]}', 'Old-Fashioned.jpg', 'The Unforgettables'),
(22, NULL, 'Paradise', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Gin\": \"30 ml\", \"Apricot Brandy\": \"20 ml\", \"Fresh Orange Juice\": \"15 ml\"}}]}', 'Paradise.jpg', 'The Unforgettables'),
(23, NULL, 'Planter\'s Punch', '{\"recipe\": [{\"Method\": \"Pour all ingredients directly in a small tumbler or a typical terracotta glass. NOTE: Add dilution up to taste, it can be given by water, ice or fresh juices.\", \"Garnish\": \"Garnish with orange zest.\", \"Ingredients\": {\"Lime Juice\": \"15 ml\", \"Jamaican Rum\": \"45 ml\", \"Sugar Cane Juice\": \"30 ml\"}}]}', 'Planters-Punch.jpg', 'The Unforgettables'),
(24, NULL, 'Porto Flip', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.\", \"Garnish\": \"Sprinkle with fresh ground nutmeg.\", \"Ingredients\": {\"Brandy\": \"15 ml\", \"Egg Yolk\": \"10 ml\", \"Red Tawny Port Wine\": \"45 ml\"}}]}', 'Porto-Flip.jpg', 'The Unforgettables'),
(25, NULL, 'Ramos Fizz', '{\"recipe\": [{\"Method\": \"Pour all ingredients except soda water in a cocktail shaker with ice, Shake for two minutes, double strain in a glass, pour the drink back in the shaker, and hard shake without ice for one minute. Strain into a highball glass, top up with soda.\", \"Garnish\": \"\", \"Ingredients\": {\"Gin\": \"45 ml\", \"Cream\": \"60 ml\", \"Egg white\": \"30 ml\", \"Soda Water\": \"30 ml\", \"Sugar Syrup\": \"30 ml\", \"Vanilla Extract\": \"2 Drops\", \"Fresh Lime Juice\": \"15 ml\", \"Fresh Lemon Juice\": \"15 ml\", \"Orange Flower Water\": \"3 Dashes\"}}]}', 'Ramos-Fizz.jpg', 'The Unforgettables'),
(26, NULL, 'Rusty Nail', '{\"recipe\": [{\"Method\": \"Pour all ingredients directly into an old fashioned glass filled with ice. Stir gently.\", \"Garnish\": \"Garnish with lemon zest.\", \"Ingredients\": {\"Drambuie\": \"25 ml\", \"Scotch Whisky\": \"45 ml\"}}]}', 'Rusty-Nail.jpg', 'The Unforgettables'),
(27, NULL, 'Sazerac', '{\"recipe\": [{\"Method\": \"Rinse a chilled old fashioned glass with the absinthe, add crushed ice and set it aside. Stir the remaining ingredients over ice in a mixing glass. Discard the ice and any excess absinthe from the prepared glass, strain the mixed drink into the glass.\", \"Garnish\": \"Garnish with lemon zest.\", \"Ingredients\": {\"Cognac\": \"50 ml\", \"Absinthe\": \"10 ml\", \"Sugar Cube\": \"1\", \"Peychauds Bitters\": \"2 Dashes\"}}]}', 'Sazerac.jpg', 'The Unforgettables'),
(28, NULL, 'Sidecar', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Cognac\": \"50 ml\", \"Triple Sec\": \"20 ml\", \"Fresh Lemon Juice\": \"20 ml\"}}]}', 'Sidecar.jpg', 'The Unforgettables'),
(29, NULL, 'Stinger', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.\", \"Garnish\": \"Optional mint leave.\", \"Ingredients\": {\"Cognac\": \"50 ml\", \"White Creme de Menthe\": \"20 ml\"}}]}', 'Stinger.jpg', 'The Unforgettables'),
(30, NULL, 'Tuxedo', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.\", \"Garnish\": \"Garnish with cherry and lemon zest\", \"Ingredients\": {\"Absinthe\": \"1/4 Bar Spoon\", \"Old Tom Gin\": \"30 ml\", \"Dry Vermouth\": \"30 ml\", \"Orange Bitters\": \"3 Dashes\", \"Maraschino Luxardo\": \"1/2 Bar Spoon\"}}]}', 'Tuxedo.jpg', 'The Unforgettables'),
(31, NULL, 'Vieux Carre', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into a chilled cocktail glass.\", \"Garnish\": \"Garnish with orange zest and maraschino cherry.\", \"Ingredients\": {\"Cognac\": \"30 ml\", \"Benedictine\": \"1 Bar Spoon\", \"Rye Whiskey\": \"30 ml\", \"Sweet Vermouth\": \"30 ml\", \"Peychauds Bitters\": \"2 Dashes\"}}]}', 'Vieux-Carre.jpg', 'The Unforgettables'),
(32, NULL, 'Whiskey Sour', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker filled with ice. Shake well. Strain into cobbler glass. If served On the rocks, strain ingredients into an old fashioned glass filled with ice. NOTE: If egg white is used shake little harder to release and incorporate the foam from the egg white.\", \"Garnish\": \"Garnish with a half orange slice and maraschino cherry, optionally use orange zest.\", \"Ingredients\": {\"Egg White\": \"20 ml (Optional)\", \"Sugar Syrup\": \"20 ml\", \"Bourbon Whiskey\": \"45 ml\", \"Fresh Lemon Juice\": \"25 ml\"}}]}', 'Whiskey-Sour.jpg', 'The Unforgettables'),
(33, NULL, 'White Lady', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Gin\": \"40 ml\", \"Triple Sec\": \"30 ml\", \"Fresh Lemon Juice\": \"20 ml\"}}]}', 'White-Lady.jpg', 'The Unforgettables'),
(34, NULL, 'Bellini', '{\"recipe\": [{\"Method\": \"Pour peach puree into the mixing glass with ice, add the Prosecco wine. Stir gently and pour in a chilled flute glass. Note: PUCCINI - Fresh Mandarin Orange Juice; ROSSINI - Fresh Strawberry Puree; TINTORETTO - Fresh Pomegranate Juice.\", \"Garnish\": \"\", \"Ingredients\": {\"Prosecco\": \"100 ml\", \"White Peach Puree\": \"50 ml\"}}]}', 'Bellini.jpg', 'Contempory Classics'),
(35, NULL, 'Black Russian', '{\"recipe\": [{\"Method\": \"Pour the ingredients into the old fashioned glass filled with ice cubes. Stir gently. Note: WHITE RUSSIAN - Float fresh cream on the top and stir in slowly.\", \"Garnish\": \"\", \"Ingredients\": {\"Vodka\": \"50 ml\", \"Coffee Liqueur\": \"20 ml\"}}]}', 'Black-Russian.jpg', 'Contempory Classics'),
(36, NULL, 'Bloody Mary', '{\"recipe\": [{\"Method\": \"Stir gently all the ingredients in a mixing glass with ice, pour into rocks glass. Note: If requested served with ice, pour into highball glass.\", \"Garnish\": \"Celery, Lemon Wedge (Optional)\", \"Ingredients\": {\"Vodka\": \"45 ml\", \"Tomato Juice\": \"90 ml\", \"Fresh Lemon Juice\": \"15 ml\", \"Worcestershire Sauce\": \"2 Dashes\", \"Tabasco, Celery Salt, Pepper\": \"To taste\"}}]}', 'Bloody-Mary.jpg', 'Contempory Classics'),
(37, NULL, 'Caipirinha', '{\"recipe\": [{\"Method\": \"Place lime and sugar into a double old fashioned glass and muddle gently. Fill the glass with cracked ice and add Cachaca. Stir gently to involve ingredients. Note: CAIPIROSKA - Instead of Cachaca use Vodka;\", \"Garnish\": \"\", \"Ingredients\": {\"Cachaca\": \"60 ml\", \"Lime Wedges\": \"4\", \"White Cane Sugar\": \"4 Teasponns\"}}]}', 'Caipirinha.jpg', 'Contempory Classics'),
(38, NULL, 'Champagne Cocktail', '{\"recipe\": [{\"Method\": \"Place the sugar cube with 2 dashes of bitters in a large Champagne glass, add the cognac. Pour gently chilled Champagne.\", \"Garnish\": \"Garnish with orange zest and maraschino cherry.\", \"Ingredients\": {\"Cognac\": \"10 ml\", \"Champagne\": \"90 ml\", \"Sugar Cube\": \"1\", \"Grand Marnier\": \"3 Drops (Optional)\", \"Angostura bitters\": \"2 Dashes\"}}]}', 'Champagne-Cocktail.jpg', 'Contempory Classics'),
(39, NULL, 'Corpse Reviver #2', '{\"recipe\": [{\"Method\": \"Pour all ingredients into shaker with ice. Shake well and strain in chilled cocktail glass.\", \"Garnish\": \"Garnish with orange zest\", \"Ingredients\": {\"Gin\": \"30 ml\", \"Absinthe\": \"1 Dash\", \"Cointreau\": \"30 ml\", \"Lillet Blanc\": \"30 ml\", \"Fresh Lemon Juice\": \"30 ml\"}}]}', 'Corpse-Reviver-2.jpg', 'Contempory Classics'),
(40, NULL, 'Cosmopolitan', '{\"recipe\": [{\"Method\": \"Add all ingredients into a cocktail shaker filled with ice. Shake well and strain into a large cocktail glass.\", \"Garnish\": \"Garnish with a lemon twist.\", \"Ingredients\": {\"Cointreau\": \"15 ml\", \"Vodka Citron\": \"40 ml\", \"Fresh Lime Juice\": \"30 ml\"}}]}', 'Cosmopolitan.jpg', 'Contempory Classics'),
(41, NULL, 'Cuba Libre', '{\"recipe\": [{\"Method\": \"Build all ingredients in a highball glass filled with ice.\", \"Garnish\": \"Garnish with lime wedge.\", \"Ingredients\": {\"Coca Cola\": \"120 ml\", \"White Rum\": \"50 ml\", \"Fresh Lime Juice\": \"10 ml\"}}]}', 'Cuba-Libre.jpg', 'Contempory Classics'),
(42, NULL, 'French 75', '{\"recipe\": [{\"Method\": \"Pour all the ingredients, except Champagne, into a shaker. Shake well and strain into a Champagne flute. Top up with Champagne. Stir gently.\", \"Garnish\": \"\", \"Ingredients\": {\"Gin\": \"30 ml\", \"Champagne\": \"60 ml\", \"Sugar Syrup\": \"15 ml\", \"Fresh Lemon Juice\": \"15 ml\"}}]}', 'French-75.jpg', 'Contempory Classics'),
(43, NULL, 'French Connection', '{\"recipe\": [{\"Method\": \"Pour all ingredients directly into an old fashioned glass filled with ice cubes. Stir gently.\", \"Garnish\": \"\", \"Ingredients\": {\"Cognac\": \"35 ml\", \"Amaretto\": \"35 ml\"}}]}', 'French-Connection.jpg', 'Contempory Classics'),
(44, NULL, 'Golden Dream', '{\"recipe\": [{\"Method\": \"Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Galliano\": \"20 ml\", \"Triple Sec\": \"20 ml\", \"Fresh Cream\": \"10 ml\", \"Fresh Orange Juice\": \"20 ml\"}}]}', 'Golden-Dream.jpg', 'Contempory Classics'),
(45, NULL, 'Grasshopper', '{\"recipe\": [{\"Method\": \"Pour all ingredients into shaker filled with ice. Shake briskly for few seconds. Strain into chilled cocktail glass.\", \"Garnish\": \"Optional mint leaf\", \"Ingredients\": {\"Fresh Cream\": \"20 ml\", \"Creme de Cacao (White)\": \"20 ml\", \"Creme de Menthe (Green)\": \"20 ml\"}}]}', 'Grasshopper.jpg', 'Contempory Classics'),
(46, NULL, 'Hemingway Special', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a shaker with ice. Shake well and strain into a large cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Rum\": \"60 ml\", \"Fresh Lime\": \"15 ml\", \"Grapefruit Juice\": \"40 ml\", \"Maraschino Luxardo\": \"15 ml\"}}]}', 'Hemingway-Special.jpg', 'Contempory Classics'),
(47, NULL, 'Horse\'s Neck', '{\"recipe\": [{\"Method\": \"Pour Cognac and ginger ale directly into a highball glass with ice cubes. Stir gently. If preferred, add dashes of Angostura Bitter.\", \"Garnish\": \"Garnish with a rind of one lemon spiral.\", \"Ingredients\": {\"Cognac\": \"40 ml\", \"Ginger Ale\": \"120 ml\", \"Angostura Bitters\": \"1 Dash (Optional)\"}}]}', 'Horse\'s-Neck.jpg', 'Contempory Classics'),
(48, NULL, 'Irish Coffee', '{\"recipe\": [{\"Method\": \"Warm black coffee is poured into a pre-heated Irish coffee glass. Whiskey and at least one teaspoon of sugar is added and stirred until dissolved. Fresh thick chilled cream is carefully poured over the back of a spoon held just above the surface of the coffee. The layer of cream will float on the coffee without mixing. Plain sugar can be replaced with sugar syrup\", \"Garnish\": \"\", \"Ingredients\": {\"Sugar\": \"1 Teaspoon\", \"Hot Coffee\": \"120 ml\", \"Fresh cream\": \"50 ml\", \"Irish Whiskey\": \"50 ml\"}}]}', 'Irish-Coffee.jpg', 'Contempory Classics'),
(49, NULL, 'Kir', '{\"recipe\": [{\"Method\": \"Pour Creme de Cassis into glass, top up with white wine. Note: KIR ROYAL - Use Champagne instead of white wine\", \"Garnish\": \"\", \"Ingredients\": {\"Dry White Wine\": \"90 ml\", \"Creme de Cassis\": \"10 ml\"}}]}', 'Kir.jpg', 'Contempory Classics'),
(50, NULL, 'Long Island Ice Tea', '{\"recipe\": [{\"Method\": \"Add all ingredients into a highball glass filled with ice. Stir gently.\", \"Garnish\": \"Lemon Slice (Optional)\", \"Ingredients\": {\"Gin\": \"15 ml\", \"Vodka\": \"15 ml\", \"Tequila\": \"15 ml\", \"Coca Cola\": \"20 ml\", \"Cointreau\": \"15 ml\", \"White rum\": \"15 ml\", \"Lemon juice\": \"30 ml\", \"Simple syrup\": \"20 ml\"}}]}', 'Long-Island-Ice-Tea.jpg', 'Contempory Classics'),
(51, NULL, 'Mai Tai', '{\"recipe\": [{\"Method\": \"Add all ingredients into a shaker with ice. Shake and pour into a double rocks glass or a highball glass.\", \"Garnish\": \"Garnish with pineapple spear, mint leaves, and lime peel.\", \"Ingredients\": {\"Simple Syrup\": \"7.5 ml\", \"Orange Curacao\": \"15 ml\", \"Fresh Lime Juice\": \"30 ml\", \"Amber Jamaican Rum\": \"30 ml\", \"Orgeat Syrup (Almond)\": \"15 ml\", \"Martinique Molasses Rhum\": \"30 ml\"}}]}', 'Mai-Tai.jpg', 'Contempory Classics'),
(52, NULL, 'Margarita', '{\"recipe\": [{\"Method\": \"Add all ingredients into a shaker with ice. Shake and strain into a chilled cocktail glass\", \"Garnish\": \"Half salt rim (Optional)\", \"Ingredients\": {\"Triple Sec\": \"20 ml\", \"Fresh Lime Juice\": \"15 ml\", \"Tequila 100% Agave\": \"50 ml\"}}]}', 'Margarita.jpg', 'Contempory Classics'),
(53, NULL, 'Mimosa', '{\"recipe\": [{\"Method\": \"Pour orange juice into a flute glass and gently pour the sparkling wine. Stir gently. Note: Also known as Bucks Fizz.\", \"Garnish\": \"Garnish with an orange twist (optional).\", \"Ingredients\": {\"Prosecco\": \"75 ml\", \"Fresh orange juice\": \"75 ml\"}}]}', 'Mimosa.jpg', 'Contempory Classics'),
(54, NULL, 'Mint Julep', '{\"recipe\": [{\"Method\": \"In Julep Stainless Steel Cup gently muddle the mint with sugar and water. Fill the glass with cracked ice, add the Bourbon and stir well until the cup frosts.\", \"Garnish\": \"Garnish with a mint sprig.\", \"Ingredients\": {\"Water\": \"2 Teaspoon\", \"Powdered Sugar\": \"1 Teaspoon\", \"Bourbon Whiskey\": \"60 ml\", \"fresh Mint sprigs\": \"4\"}}]}', 'Mint-Julep.jpg', 'Contempory Classics'),
(55, NULL, 'Mojito', '{\"recipe\": [{\"Method\": \"Mix mint springs with sugar and lime juice. Add splash of soda water and fill the glass with ice. Pour the rum and top with soda water. Light stir to involve all ingredients.\", \"Garnish\": \"Garnish with sprigs of mint and slice of lime.\", \"Ingredients\": {\"Soda Water\": \"30 ml\", \"White Cuban Ron\": \"45 ml\", \"Fresh Lime Juice\": \"20 ml\", \"White Cane Sugar\": \"2 Teaspoons\", \"Fresh Mint Sprigs\": \"6\"}}]}', 'Mojito.jpg', 'Contempory Classics'),
(56, NULL, 'Moscow Mule', '{\"recipe\": [{\"Method\": \"In a Mule Cup or rocks glass, combine the vodka and ginger beer. Add lime juice and gently stir to involve all ingredients.\", \"Garnish\": \"Garnish with a lime slice\", \"Ingredients\": {\"Vodka\": \"45 ml\", \"Ginger Beer\": \"120 ml\", \"Fresh lime juice\": \"10 ml\"}}]}', 'Moscow-Mule.jpg', 'Contempory Classics'),
(57, NULL, 'Pina Colada', '{\"recipe\": [{\"Method\": \"Blend all the ingredients with ice in an electric blender, pour into a large glass, and serve with straws.\", \"Garnish\": \"Garnish with a slice of pineapple with a cocktail cherry.\", \"Ingredients\": {\"White Rum\": \"50 ml\", \"Coconut Cream\": \"30 ml\", \"Fresh Pineapple Juice\": \"50 ml\"}}]}', 'Pina-Colada.jpg', 'Contempory Classics'),
(58, NULL, 'Pisco Sour', '{\"recipe\": [{\"Method\": \"Add all ingredients into a shaker with ice. Shake and strain into a chilled goblet glass.\", \"Garnish\": \"Few dashes of Amargo bitters on top as an aromatic garnish.\", \"Ingredients\": {\"Pisco\": \"60 ml\", \"Simple Syrup\": \"20 ml\", \"Raw Egg White\": \"1\", \"Fresh Lemon Juice\": \"30 ml\"}}]}', 'Pisco-Sour.jpg', 'Contempory Classics'),
(59, NULL, 'Sea Breeze', '{\"recipe\": [{\"Method\": \"Build all ingredients in a highball glass filled with ice.\", \"Garnish\": \"Garnish with orange zest and cherry\", \"Ingredients\": {\"Vodka\": \"40 ml\", \"Cranberry Juice\": \"120 ml\", \"Grapefruit Juice\": \"30 ml\"}}]}', 'Sea-Breeze.jpg', 'Contempory Classics'),
(60, NULL, 'Sex On The Beach', '{\"recipe\": [{\"Method\": \"Build all ingredients in a highball glass filled with ice.\", \"Garnish\": \"Garnish with a half orange slice.\", \"Ingredients\": {\"Vodka\": \"40 ml\", \"Peach Schnapps\": \"20 ml\", \"Cranberry Juice\": \"40 ml\", \"Fresh Orange Juice\": \"40 ml\"}}]}', 'Sex-On-The-Beach.jpg', 'Contempory Classics'),
(61, NULL, 'Singapore Sling', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker filled with ice cubes. Shake well. Strain into Hurricane glass.\", \"Garnish\": \"Garnish with pineapple and maraschino cherry\", \"Ingredients\": {\"Gin\": \"30 ml\", \"Cointreau\": \"7.5 ml\", \"Cherry liqueur\": \"15 ml\", \"DOM Benedictine\": \"7.5 ml\", \"Grenadine Syrup\": \"10 ml\", \"Fresh Lime Juice\": \"15 ml\", \"Angostura bitters\": \"1 Dash\", \"Fresh Pineapple Juice\": \"120 ml\"}}]}', 'Singapore-Sling.jpg', 'Contempory Classics'),
(62, NULL, 'Tequila Sunrise', '{\"recipe\": [{\"Method\": \"Pour tequila and orange juice directly into highball glass filled with ice cubes. Add the grenadine syrup to create chromatic effect (sunrise), do not stir.\", \"Garnish\": \"Garnish with half orange slice or an orange zest\", \"Ingredients\": {\"Tequila\": \"45 ml\", \"Grenadine Syrup\": \"15 ml\", \"Fresh Orange Juice\": \"90 ml\"}}]}', 'Tequila-Sunrise.jpg', 'Contempory Classics'),
(63, NULL, 'Vesper', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker filled with ice cubes. Shake and strain into a chilled cocktail glass.\", \"Garnish\": \"Lemon zest\", \"Ingredients\": {\"Gin\": \"45 ml\", \"Vodka\": \"15 ml\", \"Lillet Blanc\": \"7.5 ml\"}}]}', 'Vesper.jpg', 'Contempory Classics'),
(64, NULL, 'Zombie', '{\"recipe\": [{\"Method\": \"Add all ingredients into an electric blender with 170 grams of cracked ice. With pulse bottom blend for a few seconds. Serve in a tall tumbler glass. Note: Donns Mix: 2 parts of fresh yellow grapefruit and 1 part of cinnamon syrup\", \"Garnish\": \"Garnish with mint leaves.\", \"Ingredients\": {\"Pernod\": \"6 Drops\", \"Falernum\": \"15 ml\", \"Donns Mix\": \"15 ml\", \"Demerara Rum\": \"30 ml\", \"Grenadine syrup\": \"1 Teaspoon\", \"Fresh lime juice\": \"20 ml\", \"Angostura bitters\": \"1 Dash\", \"Jamaican dark rum\": \"45 ml\", \"Gold Puerto Rican rum\": \"45 ml\"}}]}', 'Zombie.jpg', 'Contempory Classics'),
(65, NULL, 'Barracuda', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker except the Prosecco, shake well with ice, strain into chilled highball glass filled with ice and top up with Prosecco.\", \"Garnish\": \"Pineapple and Cherry, optional mint sprig for additional aroma.\", \"Ingredients\": {\"Galliano\": \"15 ml\", \"Gold Rum\": \"45 ml\", \"Prosecco\": \"Top up\", \"Fresh Lime Juice\": \"1 Dash\", \"Fresh Pineapple Juice\": \"60 ml\"}}]}', 'Barracuda.jpg', 'New Era Drinks'),
(66, NULL, 'Bee\'s Knees', '{\"recipe\": [{\"Method\": \"Stir honey with lemon and orange juices until it dissolves, add gin and shake with ice. Strain into a chilled cocktail glass.\", \"Garnish\": \"Optionally garnish with a lemon or orange zest.\", \"Ingredients\": {\"Dry Gin\": \"52.5 ml\", \"Honey Syrup\": \"2 Teaspoons\", \"Fresh Lemon Juice\": \"22.5 ml\", \"Fresh Orange Juice\": \"22.5 ml\"}}]}', 'Bees-Knees.jpg', 'New Era Drinks'),
(67, NULL, 'Bramble', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker except the Creme de Mure, shake well with ice, strain into chilled old fashioned glass filled with crushed ice, then pour the blackberry liqueur (Creme de Mure) over the top of the drink, in a circular motion.\", \"Garnish\": \"Garnish optionally with a lemon slice and blackberries.\", \"Ingredients\": {\"Gin\": \"50 ml\", \"Sugar Syrup\": \"12.5 ml\", \"Creme de Mure\": \"15 ml\", \"Fresh Lemon Juice\": \"25 ml\"}}]}', 'Bramble.jpg', 'New Era Drinks'),
(68, NULL, 'Canchanchara', '{\"recipe\": [{\"Method\": \"Mix honey with water and lime juice and spread the mixture on the bottom and sides of the glass. Add cracked ice, and then the rum. End by energetically stirring from bottom to top.\", \"Garnish\": \"Lime wedge.\", \"Ingredients\": {\"Water\": \"50 ml\", \"Raw Honey\": \"15 ml\", \"Fresh Lime Juice\": \"15 ml\", \"Cuban Aguardiente\": \"60 ml\"}}]}', 'Canchanchara.jpg', 'New Era Drinks'),
(69, NULL, 'Dark \'n\' Stormy', '{\"recipe\": [{\"Method\": \"In a highball glass filled with ice pour the ginger beer and top floating with the Rum.\", \"Garnish\": \"Garnish with a lime wedge or slice.\", \"Ingredients\": {\"Ginger Beer\": \"100 ml\", \"Goslings Rum\": \"60 ml\"}}]}', 'DarkNStormy.jpg', 'New Era Drinks'),
(70, NULL, 'Espresso Martini', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Vodka\": \"50 ml\", \"Kahlua\": \"30 ml\", \"Sugar Syrup\": \"10 ml\", \"strong Espresso\": \"1\"}}]}', 'Espresso-Martini.jpg', 'New Era Drinks'),
(71, NULL, 'Fernandito', '{\"recipe\": [{\"Method\": \"Pour the Fernet Branca into a double old fashioned glass with ice, fill the glass up with Cola. Gently stir.\", \"Garnish\": \"\", \"Ingredients\": {\"Cola\": \"Top Off\", \"Fernet Branca\": \"50 ml\"}}]}', 'Fernandito.jpg', 'New Era Drinks'),
(72, NULL, 'French martini', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"Squeeze oil from lemon peel onto the drink.\", \"Ingredients\": {\"Vodka\": \"45 ml\", \"Raspberry Liqueur\": \"15 ml\", \"Fresh Pineapple Juice\": \"15 ml\"}}]}', 'French-Martini.jpg', 'New Era Drinks'),
(73, NULL, 'Illegal', '{\"recipe\": [{\"Method\": \"Pour all ingredients into the shaker. Shake vigorously with ice.  Strain into a chilled cocktail glass, or on the rocks in a traditional clay or terracotta mug.\", \"Garnish\": \"\", \"Ingredients\": {\"Falernum\": \"15 ml\", \"Egg White\": \"Few Drops (Optional)\", \"Simple Syrup\": \"15 ml\", \"Espadin Mezcal\": \"30 ml\", \"Fresh Lime Juice\": \"22.5 ml\", \"Maraschino Luxardo\": \"1 Bar Spoon\", \"Jamaica Overproof White Rum\": \"15 ml\"}}]}', 'Illegal.jpg', 'New Era Drinks'),
(74, NULL, 'Lemon Drop Martini', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"Garnish with sugar rim around the glass.\", \"Ingredients\": {\"Triple Sec\": \"20 ml\", \"Vodka Citron\": \"30 ml\", \"Fresh Lemon Juice\": \"15 ml\"}}]}', 'Lemon-Drop-Martini.jpg', 'New Era Drinks'),
(75, NULL, 'Naked and Famous', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Aperol\": \"22.5 ml\", \"Mezcal\": \"22.5 ml\", \"Fresh Lime Juice\": \"22.5 ml\", \"Yellow Chartreuse\": \"22.5 ml\"}}]}', 'Naked-and-Famous.jpg', 'New Era Drinks'),
(76, NULL, 'New York Sour', '{\"recipe\": [{\"Method\": \"Pour all ingredients into the shaker. Shake vigorously with ice.  Strain into a chilled rocks glass filled with ice. Float the wine on top.\", \"Garnish\": \"Garnish with lemon or orange zest with cherry.\", \"Ingredients\": {\"Red wine\": \"15 ml\", \"Egg White\": \"Few Drops\", \"Simple syrup\": \"22.5 ml\", \"Fresh lemon juice\": \"30 ml\", \"Rye Whiskey or Bourbon\": \"60 ml\"}}]}', 'New-York-Sour.jpg', 'New Era Drinks'),
(77, NULL, 'Old Cuban', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker except the wine, shake well with ice, strain into chilled elegant cocktail glass. Top up with the sparkling wine.\", \"Garnish\": \"Garnish with mint springs.\", \"Ingredients\": {\"Aged Rum\": \"45 ml\", \"Mint Leaves\": \"6 Pieces\", \"Simple Syrup\": \"30 ml\", \"Fresh Lime Juice\": \"22.5 ml\", \"Angostura Bitters\": \"2 Dashes\", \"Brut Champagne or Prosecco\": \"60 ml\"}}]}', 'Old-Cuban.jpg', 'New Era Drinks'),
(78, NULL, 'Paloma', '{\"recipe\": [{\"Method\": \"Poor the tequila into a highball glass, squeeze the lime juice. Add ice and salt, fill up pink grapefruit soda. Stir gently.\", \"Garnish\": \"Garnish with a slice of lime.\", \"Ingredients\": {\"Salt\": \"A Pinch\", \"Fresh lime\": \"5 ml\", \"100% Agave Tequila\": \"50 ml\", \"Pink Grapefruit Soda\": \"100 ml\"}}]}', 'Paloma.jpg', 'New Era Drinks'),
(79, NULL, 'Paper Plane', '{\"recipe\": [{\"Method\": \"Pour all ingredients into cocktail shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Aperol\": \"30 ml\", \"Amaro Nonino\": \"30 ml\", \"Bourbon Whiskey\": \"30 ml\", \"Fresh Lemon Juice\": \"30 ml\"}}]}', 'Paper-Plane.jpg', 'New Era Drinks'),
(80, NULL, 'Penicillin', '{\"recipe\": [{\"Method\": \"Muddle fresh ginger in a shaker and add the remaining ingredients, except for the Islay single malt whiskey. Fill the shaker with ice and shake. Double-strain into a chilled old fashioned glass with ice. Float the single malt whisky on top.\", \"Garnish\": \"Garnish with candied ginger.\", \"Ingredients\": {\"Honey Syrup\": \"22.5 ml\", \"Fresh Lemon Juice\": \"22.5 ml\", \"Sliced Fresh Ginger\": \"3\", \"Lagavulin 16y Whisky\": \"7.5 ml\", \"Blended Scotch Whisky\": \"60 ml\"}}]}', 'Penicillin.jpg', 'New Era Drinks'),
(81, NULL, 'Russian Spring Punch', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker except the sparkling wine, shake well with ice, strain into a chilled tall tumbler glass filled with ice, and top up with sparkling wine.\", \"Garnish\": \"Garnish with blackberries and optionally a lemon slice as well.\", \"Ingredients\": {\"Vodka\": \"25 ml\", \"Sugar syrup\": \"10 ml\", \"Sparkling wine\": \"Top Off\", \"Creme de Cassis\": \"15 ml\", \"Fresh Lemon Juice\": \"25 ml\"}}]}', 'Russian-Spring-Punch.jpg', 'New Era Drinks'),
(82, NULL, 'Southside', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass. Note: If egg white is used shake vigorously.\", \"Garnish\": \"Garnish with mint springs.\", \"Ingredients\": {\"Egg White\": \"Few Drops (Optional)\", \"Mint Leaves\": \"5\", \"Simple Syrup\": \"15 ml\", \"London Dry Gin\": \"60 ml\", \"Fresh Lemon Juice\": \"30 ml\"}}]}', 'Southside.jpg', 'New Era Drinks'),
(83, NULL, 'Spicy Fifty', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, double-strain into chilled cocktail glass.\", \"Garnish\": \"Garnish with a red chili pepper\", \"Ingredients\": {\"Vodka Vanilla\": \"50 ml\", \"Fresh Lime Juice\": \"15 ml\", \"Monin Honey Syrup\": \"10 ml\", \"Elderflower Cordial\": \"15 ml\", \"Sliced Red Chili Pepper\": \"2\"}}]}', 'Spicy-Fifty.jpg', 'New Era Drinks'),
(84, NULL, 'Spritz', '{\"recipe\": [{\"Method\": \"Build all ingredients into a wine glass filled with ice. Stir gently. NOTE: There are other versions of the Spritz that use Campari, Cynar or Select instead of Aperol.\", \"Garnish\": \"Garnish with a slice of orange.\", \"Ingredients\": {\"Aperol\": \"60 ml\", \"Prosecco\": \"90 ml\", \"Soda water\": \"A Splash\"}}]}', 'Spritz.jpg', 'New Era Drinks'),
(85, NULL, 'Suffering Bastard', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker except the ginger beer, shake well with ice, Pour unstrained into a Collins glass or in the original S. Bastard mug and top up with ginger beer.\", \"Garnish\": \"Garnish with mint springs and optionally an orange slice as well.\", \"Ingredients\": {\"Gin\": \"30 ml\", \"Ginger beer\": \"Top Off\", \"Cognac or Brandy\": \"30 ml\", \"Fresh Lime Juice\": \"30 ml\", \"Angostura Bitters\": \"2 Dashes\"}}]}', 'Suffering-Bastard.jpg', 'New Era Drinks'),
(86, NULL, 'Tipperary', '{\"recipe\": [{\"Method\": \"Pour all ingredients into mixing glass with ice cubes. Stir well. Strain into chilled martini cocktail glass.\", \"Garnish\": \"Garnish with a slice of orange.\", \"Ingredients\": {\"Irish Whiskey\": \"50 ml\", \"Green Chartreuse\": \"15 ml\", \"Angostura Bitters\": \"2 Dashes\", \"Sweet Red Vermouth\": \"25 ml\"}}]}', 'Tipperary.jpg', 'New Era Drinks'),
(87, NULL, 'Tommy\'s Margarita', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled rocks glass filled with ice.\", \"Garnish\": \"Garnish with a lime slice.\", \"Ingredients\": {\"Fresh Lime Juice (Persiano)\": \"30 ml\", \"Tequila Agave 100% Reposado\": \"60 ml\", \"Agave Syrup (1/2 Water + 1/2 Agave Nectar)\": \"30 ml\"}}]}', 'Tommys-Margarita.jpg', 'New Era Drinks'),
(88, NULL, 'Trinidad Sour', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into a chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Rye Whisky\": \"15 ml\", \"Orgeat Syrup\": \"30 ml\", \"Angostura Bitters\": \"45 ml\", \"Fresh Lemon Juice\": \"22.5 ml\"}}]}', 'Trinidad-Sour.jpg', 'New Era Drinks'),
(89, NULL, 'Ve.n.to', '{\"recipe\": [{\"Method\": \"Pour all ingredients into the shaker. Shake vigorously with ice.  Strain into a chilled small tumbler glass filled with ice. Notes: If desired water can be replaced by chamomile infusion in the honey mix.\", \"Garnish\": \"Garnish with lemon zest and white grapes.\", \"Ingredients\": {\"Egg White\": \"10 ml (Optional)\", \"Honey mix\": \"15 ml\", \"Chamomile cordial\": \"15 ml\", \"Fresh lemon Juice\": \"22.5 ml\", \"White Smooth Grappa\": \"45 ml\"}}]}', 'Ve.n.to.jpg', 'New Era Drinks'),
(90, NULL, 'Yellow Bird', '{\"recipe\": [{\"Method\": \"Pour all ingredients into a cocktail shaker, shake well with ice, strain into chilled cocktail glass.\", \"Garnish\": \"\", \"Ingredients\": {\"Galliano\": \"15 ml\", \"White rum\": \"30 ml\", \"Triple Sec\": \"15 ml\", \"Fresh Lime Juice\": \"15 ml\"}}]}', 'Yellow-Bird.jpg', 'New Era Drinks');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `userID` int(11) NOT NULL,
  `userName` tinytext NOT NULL,
  `email` tinytext NOT NULL,
  `password` longtext NOT NULL,
  `preferences` json NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`userID`, `userName`, `email`, `password`, `preferences`) VALUES
(1, 'Big Timbo', 'timothy_amis@msn.com', '$2y$10$jjPrT6bKRUpIBX3rDgdMLerFqoFGfkybHxnWWu0rt2nT1qNk.hw92', 'null');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cocktails`
--
ALTER TABLE `cocktails`
  ADD PRIMARY KEY (`cocktailID`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`userID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cocktails`
--
ALTER TABLE `cocktails`
  MODIFY `cocktailID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=91;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `userID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
